title: Daily Stories
subtitle: Daily surrealist fiction in English
description: Daily surrealist short stories in English
author: Yuxuan Chen
language: en
timezone: America/Los_Angeles
url: https://yuxuan.ch
root: /stories/
permalink: :year/:month/:day/
source_dir: source
public_dir: public
theme: stories
pretty_urls:
  trailing_index: true
  trailing_html: true
